// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AltaSoft.Storm
{
    internal sealed partial class Vsix
    {
        public const string Id = "AltaSoft.Storm.0a02b82e-6254-4133-a480-ad539bda2680";
        public const string Name = "AltaSoft.Storm";
        public const string Description = @"AltaSoft.Storm Visual Studio Extension";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Alta Software llc.";
        public const string Tags = "";
    }
}
