// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AltaSoft.Storm
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAltaSoftStormPackageString = "0a02b82e-6254-4133-a480-ad539bda268a";
        public static Guid guidAltaSoftStormPackage = new Guid(guidAltaSoftStormPackageString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int StormCommand = 0x0100;
        public const int StormDesignCommand = 0x0101;
    }
}