name: Publish to NuGet

on:
  release:
    types: [created]

jobs:
  extract-version:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Extract version from tag
        id: set_version
        run: |
          echo "version=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_OUTPUT

  build-and-pack:
    uses: ./.github/workflows/build_and_pack.yaml
    needs: extract-version
    with:
      version: ${{ needs.extract-version.outputs.version }}

  publish:
    runs-on: windows-latest
    needs: build-and-pack
    steps:
      - name: Download NuGet packages artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkgs

      - name: Publish packages to NuGet.org
        run: dotnet nuget push "nupkgs/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
