name: Publish to NuGet

on:
  release:
    types: [created]

jobs:
  extract-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Extract version from tag
        id: set_version
        shell: bash
        run: |
          TAG="${{ github.event.release.tag_name }}" 
          VER="${TAG#v}"    
          echo "version=$VER" >> "$GITHUB_OUTPUT"

  build-and-pack:
    uses: ./.github/workflows/build_and_pack.yaml
    needs: extract-version
    with:
      version: ${{ needs.extract-version.outputs.version }}

  publish:
    runs-on: ubuntu-latest
    needs: build-and-pack
    steps:
      - name: Download NuGet packages artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkgs
          path: nupkgs

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish packages to NuGet.org
        run: dotnet nuget push "*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
        working-directory: nupkgs

